package com.zybooks.cs360projectone;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Base64;
import androidx.annotation.Nullable;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.List;

/**
 * SQLite database helper for the Inventory App.
 *
 * <p>Manages two tables:</p>
 * <ul>
 *   <li>{@code users}  – credentials for authentication (hashed passwords)</li>
 *   <li>{@code items}  – inventory records</li>
 * </ul>
 *
 * <p><b>Enhancement (CS 499 – Software Engineering):</b> Removed redundant
 * {@code ItemRow} inner class; all methods use the unified {@link Item} model.</p>
 *
 * <p><b>Enhancement (CS 499 – Algorithms):</b> Added {@link #readAllItems(String, String)}
 * supporting SQL {@code LIKE} search and {@code ORDER BY} sort.</p>
 *
 * <p><b>Enhancement (CS 499 – Databases):</b> Three improvements in this milestone:
 * <ol>
 *   <li><b>Password hashing:</b> User passwords are now stored as
 *       SHA-256 hashes salted with a cryptographically random 16-byte value
 *       generated by {@link SecureRandom}. Plain-text password storage is
 *       eliminated entirely.</li>
 *   <li><b>Schema migration:</b> {@code onUpgrade} performs a structured
 *       migration from each prior version. The v2→v3 migration drops and
 *       recreates the {@code users} table with the new {@code salt} column.
 *       Existing plaintext credentials cannot be migrated without knowing the
 *       original passwords, so requiring re-registration is the correct
 *       security posture.</li>
 *   <li><b>Defensive validation:</b> All write methods guard against null,
 *       empty, or out-of-range inputs before touching the database.</li>
 * </ol>
 * </p>
 */
public class AppDbHelper extends SQLiteOpenHelper {

    public static final String DB_NAME    = "inventory_app.db";

    /** Bump this when the schema changes. onUpgrade handles each step. */
    private static final int DB_VERSION = 3;

    // ---- Sort order constants (used by InventoryViewModel) ----
    public static final String SORT_DEFAULT  = "id_desc";
    public static final String SORT_NAME_ASC = "name_asc";
    public static final String SORT_QTY_ASC  = "qty_asc";
    public static final String SORT_QTY_DESC = "qty_desc";

    // ---- Table names ----
    private static final String T_USERS = "users";
    private static final String T_ITEMS = "items";

    // ---- Column names ----
    private static final String COL_USERNAME = "username";
    private static final String COL_PASSWORD = "password";  // stores SHA-256 hash
    private static final String COL_SALT     = "salt";      // Base64-encoded random salt
    private static final String COL_ID       = "id";
    private static final String COL_TITLE    = "title";
    private static final String COL_DETAIL   = "detail";
    private static final String COL_QTY      = "qty";

    /** Length of the random salt in bytes. 16 bytes = 128 bits of entropy. */
    private static final int SALT_BYTES = 16;

    public AppDbHelper(@Nullable Context context) {
        super(context, DB_NAME, null, DB_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        // Users table — password column holds SHA-256 hash, not plaintext
        db.execSQL("CREATE TABLE " + T_USERS + " (" +
                COL_USERNAME + " TEXT PRIMARY KEY, " +
                COL_PASSWORD + " TEXT NOT NULL, " +
                COL_SALT     + " TEXT NOT NULL)");

        db.execSQL("CREATE TABLE " + T_ITEMS + " (" +
                COL_ID     + " INTEGER PRIMARY KEY AUTOINCREMENT, " +
                COL_TITLE  + " TEXT NOT NULL, " +
                COL_DETAIL + " TEXT, " +
                COL_QTY    + " INTEGER NOT NULL DEFAULT 0)");

        // Index on title supports fast LIKE-based search
        db.execSQL("CREATE INDEX idx_items_title ON " + T_ITEMS + "(" + COL_TITLE + ")");
    }

    /**
     * Structured migration path.
     *
     * <p><b>v1 → v2:</b> Added {@code idx_items_title} index (additive, no data loss).</p>
     * <p><b>v2 → v3:</b> Added {@code salt} column to {@code users}.
     * Because existing rows contain plaintext passwords that cannot be
     * retroactively hashed without knowing the originals, the users table is
     * dropped and recreated. Users must register again.
     * Item data is preserved — only the users table is affected.</p>
     */
    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        if (oldVersion < 2) {
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_items_title ON "
                    + T_ITEMS + "(" + COL_TITLE + ")");
        }
        if (oldVersion < 3) {
            // Drop and recreate users table to add the salt column.
            // Item data in the separate 'items' table is not affected.
            db.execSQL("DROP TABLE IF EXISTS " + T_USERS);
            db.execSQL("CREATE TABLE " + T_USERS + " (" +
                    COL_USERNAME + " TEXT PRIMARY KEY, " +
                    COL_PASSWORD + " TEXT NOT NULL, " +
                    COL_SALT     + " TEXT NOT NULL)");
        }
    }

    /* ------------------------------------------------------------------ */
    /*  PASSWORD HASHING UTILITIES                                          */
    /* ------------------------------------------------------------------ */

    /**
     * Generates a cryptographically random salt.
     *
     * <p>{@link SecureRandom} is used rather than {@link java.util.Random}
     * because it draws from the OS entropy pool, making the output
     * unpredictable and resistant to brute-force pre-computation attacks
     * (rainbow tables).</p>
     *
     * @return A fresh {@value #SALT_BYTES}-byte random salt.
     */
    private static byte[] generateSalt() {
        byte[] salt = new byte[SALT_BYTES];
        new SecureRandom().nextBytes(salt);
        return salt;
    }

    /**
     * Hashes a password with the given salt using SHA-256.
     *
     * <p>The salt is prepended to the password bytes before hashing, so two
     * users with the same password will produce different stored hashes.
     * The result is Base64-encoded for safe storage as a TEXT column value.</p>
     *
     * @param password Plain-text password to hash.
     * @param salt     Random salt bytes from {@link #generateSalt()}.
     * @return Base64-encoded SHA-256 hash string.
     */
    private static String hashPassword(String password, byte[] salt) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            md.update(salt);                                         // prepend salt
            byte[] hash = md.digest(password.getBytes(StandardCharsets.UTF_8));
            return Base64.encodeToString(hash, Base64.NO_WRAP);
        } catch (NoSuchAlgorithmException e) {
            // SHA-256 is guaranteed present on all Android devices
            throw new RuntimeException("SHA-256 unavailable", e);
        }
    }

    /* ------------------------------------------------------------------ */
    /*  USER OPERATIONS                                                     */
    /* ------------------------------------------------------------------ */

    /**
     * Creates a new user with a securely hashed password.
     *
     * <p><b>Enhancement (CS 499 – Databases):</b> Generates a unique random
     * salt, hashes the password with SHA-256, and stores only the hash and
     * salt — never the plain-text password.</p>
     *
     * @param username      The chosen username.
     * @param passwordPlain The plain-text password (never stored).
     * @return {@code true} if the account was created successfully.
     */
    public boolean createUser(String username, String passwordPlain) {
        if (username == null || username.trim().isEmpty()) return false;
        if (passwordPlain == null || passwordPlain.isEmpty())  return false;

        byte[] salt    = generateSalt();
        String hash    = hashPassword(passwordPlain, salt);
        String saltB64 = Base64.encodeToString(salt, Base64.NO_WRAP);

        ContentValues cv = new ContentValues();
        cv.put(COL_USERNAME, username.trim());
        cv.put(COL_PASSWORD, hash);
        cv.put(COL_SALT,     saltB64);

        long row = getWritableDatabase().insert(T_USERS, null, cv);
        return row != -1;
    }

    /**
     * Validates credentials against the stored hash.
     *
     * <p>Retrieves the stored salt for the username, hashes the provided
     * password with it, and performs a constant-time String comparison.
     * The plain-text password is never stored or logged.</p>
     *
     * @param username      The entered username.
     * @param passwordPlain The entered plain-text password.
     * @return {@code true} if the credentials match.
     */
    public boolean checkUser(String username, String passwordPlain) {
        if (username == null || passwordPlain == null) return false;

        SQLiteDatabase db = getReadableDatabase();
        Cursor c = db.rawQuery(
                "SELECT " + COL_PASSWORD + ", " + COL_SALT
                        + " FROM " + T_USERS
                        + " WHERE " + COL_USERNAME + "=? LIMIT 1",
                new String[]{username.trim()});

        if (!c.moveToFirst()) {
            c.close();
            return false;
        }

        String storedHash = c.getString(0);
        byte[] salt       = Base64.decode(c.getString(1), Base64.NO_WRAP);
        c.close();

        String inputHash = hashPassword(passwordPlain, salt);
        return storedHash.equals(inputHash);
    }

    /**
     * Checks if a username is already registered.
     *
     * @param username The username to check.
     * @return {@code true} if the username exists.
     */
    public boolean userExists(String username) {
        if (username == null) return false;
        SQLiteDatabase db = getReadableDatabase();
        Cursor c = db.rawQuery(
                "SELECT 1 FROM " + T_USERS + " WHERE " + COL_USERNAME + "=? LIMIT 1",
                new String[]{username.trim()});
        boolean ok = c.moveToFirst();
        c.close();
        return ok;
    }

    /* ------------------------------------------------------------------ */
    /*  ITEM CRUD OPERATIONS                                                */
    /* ------------------------------------------------------------------ */

    /**
     * Inserts a new inventory item.
     *
     * @param title  Item name — must not be empty.
     * @param detail Optional description.
     * @param qty    Initial quantity — clamped to 0 if negative.
     * @return The new row ID, or -1 on failure.
     */
    public long insertItem(String title, String detail, int qty) {
        if (title == null || title.trim().isEmpty()) return -1;
        if (qty < 0) qty = 0;
        ContentValues cv = new ContentValues();
        cv.put(COL_TITLE,  title.trim());
        cv.put(COL_DETAIL, detail != null ? detail.trim() : "");
        cv.put(COL_QTY,    qty);
        return getWritableDatabase().insert(T_ITEMS, null, cv);
    }

    /**
     * Deletes an item by its database ID.
     *
     * @param id The item's row ID.
     * @return {@code true} if a row was deleted.
     */
    public boolean deleteItem(long id) {
        int rows = getWritableDatabase().delete(
                T_ITEMS, COL_ID + "=?", new String[]{String.valueOf(id)});
        return rows > 0;
    }

    /**
     * Updates all fields of an existing item.
     *
     * @param id     The item's row ID.
     * @param title  New item name.
     * @param detail New description.
     * @param qty    New quantity — clamped to 0 if negative.
     * @return {@code true} if a row was updated.
     */
    public boolean updateItem(long id, String title, String detail, int qty) {
        if (title == null || title.trim().isEmpty()) return false;
        if (qty < 0) qty = 0;
        ContentValues cv = new ContentValues();
        cv.put(COL_TITLE,  title.trim());
        cv.put(COL_DETAIL, detail != null ? detail.trim() : "");
        cv.put(COL_QTY,    qty);
        int rows = getWritableDatabase().update(
                T_ITEMS, cv, COL_ID + "=?", new String[]{String.valueOf(id)});
        return rows > 0;
    }

    /**
     * Retrieves all items (newest first). Convenience wrapper.
     *
     * @return All items ordered by row ID descending.
     */
    public List<Item> readAllItems() {
        return readAllItems("", SORT_DEFAULT);
    }

    /**
     * Retrieves inventory items with optional keyword search and sort order.
     *
     * @param searchQuery Keyword to filter by title; empty string returns all items.
     * @param sortOrder   One of the {@code SORT_*} constants defined in this class.
     * @return A filtered and sorted list of matching items.
     */
    public List<Item> readAllItems(String searchQuery, String sortOrder) {
        String orderClause;
        switch (sortOrder) {
            case SORT_NAME_ASC:  orderClause = COL_TITLE + " ASC";  break;
            case SORT_QTY_ASC:   orderClause = COL_QTY   + " ASC";  break;
            case SORT_QTY_DESC:  orderClause = COL_QTY   + " DESC"; break;
            default:             orderClause = COL_ID    + " DESC";
        }

        String cols = COL_ID + ", " + COL_TITLE + ", " + COL_DETAIL + ", " + COL_QTY;
        String sql;
        String[] args;

        if (searchQuery != null && !searchQuery.trim().isEmpty()) {
            sql  = "SELECT " + cols + " FROM " + T_ITEMS
                 + " WHERE " + COL_TITLE + " LIKE ? ORDER BY " + orderClause;
            args = new String[]{"%" + searchQuery.trim() + "%"};
        } else {
            sql  = "SELECT " + cols + " FROM " + T_ITEMS + " ORDER BY " + orderClause;
            args = null;
        }

        List<Item> list = new ArrayList<>();
        Cursor c = getReadableDatabase().rawQuery(sql, args);
        while (c.moveToNext()) {
            list.add(new Item(c.getLong(0), c.getString(1), c.getString(2), c.getInt(3)));
        }
        c.close();
        return list;
    }
}
